Update docker-build.yml

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -110,8 +110,8 @@ jobs:
       - name: Enforce code coverage threshold
         run: |
          if (( $(echo "$percentage < 80" | bc -l) )); then
-         echo "Code coverage is below 80%. Failing the workflow."
-         exit 1
+            echo "Code coverage is below 80%. Failing the workflow."
+            exit 1
          fi
 
       # Step 9: Conclusion       
