Update docker-build.yml

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -105,7 +105,15 @@ jobs:
           total=$(($coverage + $missed))
           percentage=$(echo "scale=2; $coverage*100/$total" | bc)
           echo "Code coverage: $percentage%"
-       
-      # Step 8: Conclusion       
+    
+      # Step 8: coverage threshold 
+      - name: Enforce code coverage threshold
+        run: |
+         if (( $(echo "$percentage < 80" | bc -l) )); then
+         echo "Code coverage is below 80%. Failing the workflow."
+         exit 1
+         fi
+
+      # Step 9: Conclusion       
       - name: Run tasks for other branches successfully
         run: echo "Running workflow for non-main branch."
